"""increase price precision

Revision ID: 48caf32d1d1d
Revises: c81b6d953c4b
Create Date: 2025-09-22 21:17:45.044647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48caf32d1d1d'
down_revision: Union[str, Sequence[str], None] = 'c81b6d953c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
