"""add payment and referral fields to order

Revision ID: a76ea5d9442c
Revises: 19ab5c44980a
Create Date: 2025-09-28 17:23:31.782549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76ea5d9442c'
down_revision: Union[str, Sequence[str], None] = '19ab5c44980a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - fixed manually ###
    op.add_column('order', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('order', sa.Column('provider', sa.String(length=50), nullable=True))

    # 🔹 FIX: добавил server_default='pending', иначе для старых строк без значения миграция упадёт
    op.add_column(
        'order',
        sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='pending')
    )

    op.add_column('order', sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # 🔹 FIX: оставил как есть, но уточнил nullable=False для created_at/updated_at,
    # чтобы гарантировать, что всегда будут значения
    op.add_column(
        'order',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    op.add_column(
        'order',
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )

    op.add_column('order', sa.Column('referrer_id', sa.BigInteger(), nullable=True))

    # 🔹 FIX: добавил server_default=sa.text('false'), чтобы старые строки заполнились корректно
    op.add_column(
        'order',
        sa.Column('bonus_awarded', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )

    op.add_column('order', sa.Column('bonus_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    op.create_foreign_key(None, 'order', 'user', ['referrer_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - fixed manually ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'bonus_amount')
    op.drop_column('order', 'bonus_awarded')
    op.drop_column('order', 'referrer_id')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    op.drop_column('order', 'paid_amount')

    # 🔹 FIX: удаление поля payment_status останется стандартным,
    # серверный default сам снимется при drop_column
    op.drop_column('order', 'payment_status')

    op.drop_column('order', 'provider')
    op.drop_column('order', 'transaction_id')
    # ### end Alembic commands ###
